In [10]:
import numpy as np

def normalize(v):
    """Normalize a vector."""
    norm = np.linalg.norm(v)
    if norm == 0: 
       return v
    return v / norm

# Define the initial vector A and target vector B
A = np.array([-8.06, -0.28, 6.6])
B = np.array([0, 0, 10])

# Normalize the vectors
A_norm = normalize(A)
B_norm = normalize(B)

# Calculate the cross product to find the rotation axis
u = np.cross(A_norm, B_norm)

# Normalize the rotation axis
u = normalize(u)

# Calculate the dot product to find the rotation angle
theta = np.arccos(np.dot(A_norm, B_norm))

# Components of the rotation axis
ux, uy, uz = u

# Calculate the rotation matrix using the axis-angle formula
cos_theta = np.cos(theta)
sin_theta = np.sin(theta)
one_minus_cos_theta = 1 - cos_theta

R = np.array([
    [cos_theta + ux**2 * one_minus_cos_theta, ux * uy * one_minus_cos_theta - uz * sin_theta, ux * uz * one_minus_cos_theta + uy * sin_theta],
    [uy * ux * one_minus_cos_theta + uz * sin_theta, cos_theta + uy**2 * one_minus_cos_theta, uy * uz * one_minus_cos_theta - ux * sin_theta],
    [uz * ux * one_minus_cos_theta - uy * sin_theta, uz * uy * one_minus_cos_theta + ux * sin_theta, cos_theta + uz**2 * one_minus_cos_theta]
])

# Apply the rotation matrix to the initial vector A
A_rotated = np.dot(R, A_norm)

# Scale the rotated vector to match the magnitude of the target vector B
A_rotated = A_rotated * np.linalg.norm(B)

# Display the results
print('Initial vector A:')
print(A)
print('Normalized initial vector A:')
print(A_norm)
print('Target vector B:')
print(B)
print('Normalized target vector B:')
print(B_norm)
print('Rotation axis (normalized):')
print(u)
print('Rotation angle (degrees):')
print(np.degrees(theta))
print('Rotation matrix R:')
print(R)
print('Rotated vector A:')
print(A_rotated)


Initial vector A:
[-8.06 -0.28  6.6 ]
Normalized initial vector A:
[-0.7734213  -0.02686823  0.63332266]
Target vector B:
[ 0  0 10]
Normalized target vector B:
[0. 0. 1.]
Rotation axis (normalized):
[-0.03471851  0.99939713  0.        ]
Rotation angle (degrees):
50.70431032929106
Rotation matrix R:
[[ 0.63376464 -0.01272282  0.7734213 ]
 [-0.01272282  0.99955802  0.02686823]
 [-0.7734213  -0.02686823  0.63332266]]
Rotated vector A:
[9.25366554e-16 0.00000000e+00 1.00000000e+01]


In [4]:
R_new = (9.8/10.279)*R


print(np.linalg.norm(A))

np.dot(R_new,A)

10.279338500117602


array([-1.06858966e-15, -1.11022302e-16,  9.80032273e+00])

In [5]:
#create a function to return the rotation matrix for a given vector

def create_rotation_matrix(v):
    B = np.array([0, 0, 9.8])

    #store the norm of v
    v_normz = np.linalg.norm(v)

    # Normalize the vectors
    v_norm = normalize(v)
    B_norm = normalize(B)

    # Calculate the cross product to find the rotation axis
    u = np.cross(v_norm, B_norm)

    # Normalize the rotation axis
    u = normalize(u)

    # Calculate the dot product to find the rotation angle
    theta = np.arccos(np.dot(v_norm, B_norm))

    # Components of the rotation axis
    ux, uy, uz = u

    # Calculate the rotation matrix using the axis-angle formula
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    one_minus_cos_theta = 1 - cos_theta

    R = np.array([
        [cos_theta + ux**2 * one_minus_cos_theta, ux * uy * one_minus_cos_theta - uz * sin_theta, ux * uz * one_minus_cos_theta + uy * sin_theta],
        [uy * ux * one_minus_cos_theta + uz * sin_theta, cos_theta + uy**2 * one_minus_cos_theta, uy * uz * one_minus_cos_theta - ux * sin_theta],
        [uz * ux * one_minus_cos_theta - uy * sin_theta, uz * uy * one_minus_cos_theta + ux * sin_theta, cos_theta + uz**2 * one_minus_cos_theta]
    ])

    R = (10.0/(v_normz))*R

    return R

In [6]:
np.dot(create_rotation_matrix(A),A)

array([-1.34614542e-15, -2.22044605e-16,  1.00000000e+01])

In [7]:
v_new = np.array([-7.83,1.61,5.93])
print(create_rotation_matrix(v_new))

[[ 0.6150651   0.08011721  0.79038297]
 [ 0.08011721  0.98822982 -0.16251808]
 [-0.79038297  0.16251808  0.59859144]]


In [9]:
u_new = np.array([-8.06,-0.28,6.6])
print(create_rotation_matrix(u_new))

print(np.dot(create_rotation_matrix(u_new),u_new))


[[ 0.60814773 -0.01220856  0.74215944]
 [-0.01220856  0.95915566  0.02578221]
 [-0.74215944 -0.02578221  0.60772361]]
[1.3691305e-15 0.0000000e+00 1.0000000e+01]


In [12]:
p_new = np.array([-7.91,1.98,6.1])
print(create_rotation_matrix(p_new))

print(np.dot(create_rotation_matrix(p_new),p_new))

[[ 0.61146138  0.09275305  0.76278828]
 [ 0.09275305  0.95878757 -0.19093815]
 [-0.76278828  0.19093815  0.5882438 ]]
[3.33066907e-16 0.00000000e+00 1.00000000e+01]
